site_name: SCL-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Build:
      - Build on Linux: build/linux-build.md
  - Development:
      - Codestyle: dev/codestyle.md
      - PR: dev/pr.md
  - Changelog: changelog.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences

